##########################################################
###################  开发环境的profile  ###################
##########################################################
spring:
  profiles: produce
  datasource:
      url: jdbc:mysql://172.16.0.200:3030/virtour?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password: root123
      filters: log4j,wall,mergeStat

#多数据源
guns:
  muti-datasource:
    default-dataSource-name: dataSourceGuns #默认的数据源名称
    url: jdbc:mysql://172.16.0.200:3030/biz?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root123

logging:
  level.root: info
  level.cn.ibdsr: debug
  path: logs/
  file: guns.log
