##########################################################
###################  开发环境的profile  ###################
##########################################################
spring:
  profiles: test
  datasource:
      url: jdbc:mysql://test.ibdsr.cn:3030/software_upgrade?autoReconnect=true&useUnicode=true&useSSL=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password: root123
      filters: log4j,wall,mergeStat

#多数据源
guns:
  muti-datasource:
    default-dataSource-name: dataSourceGuns #默认的数据源名称
    url: jdbc:mysql://test.ibdsr.cn:13306/software_upgrade?autoReconnect=true&useUnicode=true&useSSL=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root123
  #fastdfs文件上传
  fastDfs-url:
    trackers: 172.16.0.200:22122
    visit: http://172.16.0.200:10080/  #文件访问的URL包括端口信息

logging:
  level.root: info
  level.cn.ibdsr: debug
  path: logs/
  file: guns.log
